# Generated by Django 2.1.3 on 2019-01-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('sex', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('date_create', models.DateField(blank=True)),
                ('date_update', models.DateField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
