# Generated by Django 2.1.3 on 2019-01-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190109_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
